### ISSUE TITLE
Mutation: Cannot read property 'connections' of undefined.

### ISSUE THREAD

**Issue by WanderWal** [Metronoid/Traficulution#2]
The copy function has been updated to the version in synaptic.js.

However because of this new update Mutation has broken down and can no longer find inputConn[0].
I'd suggest reworking this function so that it works correctly and does not get all it's data from very nested connection points.

**Comment by msnijder30** [comment]
The copy function wasn't copying the connections within the brain sometimes. 
Fixed it by cloning the brain via a jQuery function ( **jQuery.extend(true, {}, entity.brain)** )
